export const RESPONSE_SCHEMA = {
  type: 'object',
  properties: {
    skillsScore: { type: 'integer' },
    experienceScore: { type: 'integer' },
    backgroundScore: { type: 'integer' },
    matchedSkills: { type: 'array', items: { type: 'string' } },
    missingSkills: { type: 'array', items: { type: 'string' } },
    strengths: { type: 'array', items: { type: 'string' } },
    weaknesses: { type: 'array', items: { type: 'string' } },
    recommendations: { type: 'array', items: { type: 'string' } },
  },
  required: [
    'skillsScore',
    'experienceScore',
    'backgroundScore',
    'matchedSkills',
    'missingSkills',
    'strengths',
    'weaknesses',
    'recommendations',
  ],
}

const buildJobMatchPrompt = (jobPayload, candidatePayload) => {
  return [
    'You are an expert technical recruiter and talent evaluation specialist.',
    'Analyze the candidate against the job description across three distinct dimensions.',
    '',
    'JOB ANALYSIS INSTRUCTIONS:',
    '- Determine the job seniority level, required skills, preferred skills, and experience expectations based ONLY on the provided job data.',
    '- If the job description does not state an experience requirement, do not invent one.',
    '- If the job states that fresh graduates or entry-level candidates are welcome, reflect that in the evaluation.',
    '',
    'CANDIDATE CONTEXT INSTRUCTIONS:',
    '- Evaluate candidate skills, yearsOfExperience, experience history, education, and projects.',
    '- Semantic meaning: if yearsOfExperience is 0 and experience is empty [], the candidate has no declared professional/commercial experience. Do not fabricate experience.',
    '',
    'DIMENSION SCORING RUBRIC (0 to 100 integer for each dimension):',
    '1. skillsScore (0-100):',
    '   - Evaluate alignment between candidate skills and job requirements.',
    '   - Distinguish required must-have skills from preferred nice-to-have skills.',
    '   - Do not treat all keyword matches as equivalent.',
    '',
    '2. experienceScore (0-100):',
    '   - Evaluate candidate experience (years, roles, internships) against the job requirements and seniority.',
    '   - CRITICAL: 0 years of experience != automatically low score.',
    '   - If the job explicitly accepts fresh graduates / interns, 0 years of experience must NOT be heavily penalized.',
    '   - If the job requires commercial / professional experience (e.g. 1+ or 2+ years), 0 years of experience represents a meaningful mismatch and must receive a lower score.',
    '   - Relevant internships count positively towards experience.',
    '   - Do not penalize candidates who possess more experience than required unless the job explicitly creates an incompatibility.',
    '   - If the job does not state an experience requirement, do not invent one or penalize arbitrarily.',
    '',
    '3. backgroundScore (0-100):',
    '   - Evaluate relevance of candidate projects, education, career summary, and domain background to the target role.',
    '   - Only use actual information provided; do not invent details.',
    '',
    'Return ONLY a valid JSON object matching this exact schema (no markdown code fences, no conversational text):',
    JSON.stringify(
      {
        skillsScore: 'integer 0 to 100 evaluating skills alignment',
        experienceScore: 'integer 0 to 100 evaluating experience alignment against job expectations',
        backgroundScore: 'integer 0 to 100 evaluating projects, education, and summary relevance',
        matchedSkills: 'skills present in both the job and the candidate',
        missingSkills: 'job skills the candidate is missing',
        strengths: 'candidate strengths relevant to this job',
        weaknesses: 'candidate gaps or weaknesses relevant to this job',
        recommendations: 'concise actionable advice to improve the fit',
      },
      null,
      2
    ),
    '',
    'Rules:',
    '- Each score (skillsScore, experienceScore, backgroundScore) MUST be an integer between 0 and 100.',
    '- Do NOT return a composite matchScore. The backend computes the final score deterministically.',
    '- matchedSkills, missingSkills, strengths, weaknesses, recommendations must each be arrays of strings.',
    '- Only use the provided job and candidate information. Do not invent details.',
    '',
    'JOB:',
    JSON.stringify(jobPayload),
    '',
    'CANDIDATE:',
    JSON.stringify(candidatePayload),
  ].join('\n')
}

export { buildJobMatchPrompt }
